### ISSUE TITLE
NN-based DPD training

### ISSUE THREAD

**Issue by AbdelwahabFawzyMohamed** [ctarver/ILA-DPD#5]
If I want to build my own Neural Network-based DPD, Do I need to perform any preprocessing either for the input or output of PA? or just use PA_out as input and PA_in as the output for the NN model during training?

**Comment by ctarver** [comment]
This is not an issue with this project so I'm closing.  If you want to have a conversation regarding your efforts in DPD, I'm happy to set up a separate call. 

That being said, yes, preprocessing data is probably a good idea. I just scale the baseband signal at the beginning of the experiment to be in an appropriate range. I found that min-max scaling wasn't the best due to the PAPR of OFDM. It's something that you should just play around with.
